### ISSUE TITLE
Show dependency metadata in the GitHub check

### ISSUE THREAD

**Issue by timja** [jenkins-infra/incrementals-publisher#22]
And a good follow-up would be to show

```xml
<dependency>
    <groupId>org.jenkins-ci.plugins</groupId>
    <artifactId>stuff</artifactId>
    <version>1.2-rcdead1234beef</version>
</dependency>
```

_Originally posted by @jglick in https://github.com/jenkins-infra/incrementals-publisher/pull/21#discussion_r784009307_

**Comment by akoolarni** [comment]
Can I work on this @maintainers

**Comment by timja** [comment]
sure

**Comment by lemeurherve** [comment]
Result: https://github.com/jenkinsci/jenkins-infra-test-plugin/pull/115#issuecomment-1937228277

<img width="450" alt="image" src="https://github.com/jenkinsci/jenkins-infra-test-plugin/assets/91831478/b1eb4845-89c4-422e-a8f1-6f915c6b25dd">

**Comment by timja** [comment]
you tried it with one that has multiple artifacts published? declarative plugin / jenkins core etc?

**Comment by lemeurherve** [comment]
> you tried it with one that has multiple artifacts published?

No. Right now it will output only the first artifact dependency metadata.

Should I make it output all artifacts? In that case, having them one after one is OK or should a specific structure be respected? (Any example?)

**Comment by timja** [comment]
Ideally all of them and if there's more than one maybe hidden behind the summary details element.

Likely for quite a few the first one won't be the interesting one.
In most cases though it's the version that's the important bit

**Comment by lemeurherve** [comment]
Result of #87 with Jenkins Core: https://github.com/jenkinsci/jenkins/pull/8827/checks?check_run_id=21444277856

<img width="550" alt="image" src="https://github.com/jenkins-infra/incrementals-publisher/assets/91831478/82575724-6a17-47aa-8c56-4d6e71aba335">

**Comment by NotMyFault** [comment]
cc @uhafner isn't that what we talked about at FOSDEM?

**Comment by lemeurherve** [comment]
I think it was #82

**Comment by NotMyFault** [comment]
> I think it was #82

Oh right, I didn't see it in prod yet 😅
