### ISSUE TITLE
Use deployments API instead of commit status

### ISSUE THREAD

**Issue by timja** [jenkins-infra/incrementals-publisher#3]

**Comment by halkeye** [comment]
So again, why? what does deployments do that checks don't in this case?

looking at https://docs.github.com/en/rest/reference/repos#create-a-deployment (and https://octokit.github.io/rest.js/v18#repos-create-deployment) it looks like creating a deployment triggers events for other systems to use? is that right?

Would you create a deployment before anything starts,
set the status to pending (https://docs.github.com/en/rest/reference/repos#create-a-deployment-status)
then do all the work
then set the status to completed (https://docs.github.com/en/rest/reference/repos#create-a-deployment-status)?

**Comment by timja** [comment]
Deployments is more obvious than a commit status I think, it separates it out from the other checks and is an explicit release I think.

You would create a deployment once the zip has been uploaded to incrementals app and before it’s been uploaded to artifactory I think

**Comment by halkeye** [comment]
I can certainly look into it, might be a good hacktober thing too.

Do you have an exmaple repo with deployments happening? i couldn't find one to see how it worked.

Otherwise i'll prototype something down the line.

**Comment by timja** [comment]
https://github.com/hmcts/rpe-pdf-service/pull/271

![image](https://user-images.githubusercontent.com/21194782/92358759-ec3dc380-f0e1-11ea-897d-548d452fc1d8.png)


https://github.com/hmcts/cnp-jenkins-library/blob/master/vars/githubCreateDeployment.groovy
https://github.com/hmcts/cnp-jenkins-library/blob/master/vars/githubUpdateDeploymentStatus.groovy

**Comment by jglick** [comment]
also see https://issues.jenkins.io/browse/JENKINS-52116

**Comment by jglick** [comment]
To be clear, #21 closes this effectively as “will not fix”.
