### ISSUE TITLE
Use GitHub app for GitHub auth

### ISSUE THREAD

**Issue by timja** [jenkins-infra/incrementals-publisher#4]

**Comment by halkeye** [comment]
Do you have a reason for this? like what are the perks? not using a specific user?

**Comment by timja** [comment]
We don’t have access to the user anymore.

So we are slowly decommissioning it, and also trying to have service credentials rather than one god credential

**Comment by halkeye** [comment]
> We don’t have access to the user anymore.

ah fair fair, i didnt't know that

I figured using app was overkill for this, doing a couple api calls an hour, but totally legit for that reason

**Comment by jglick** [comment]
See also #3 and https://issues.jenkins.io/browse/INFRA-2865
