### ISSUE TITLE
Add plugin manager syntax to checks page

### ISSUE THREAD

**Issue by timja** [jenkins-infra/incrementals-publisher#86]
### What feature do you want to see added?

It would be nice to show the plugin manager cli format on the checks summary.
Similar to https://github.com/jenkins-infra/incrementals-publisher/issues/22

see https://github.com/jenkinsci/plugin-installation-manager-tool/#plugin-input-format

e.g. 
```
lockable-resources:incrementals;org.6wind.jenkins;1323.v474b_98d41b_6a_
```

**Comment by timja** [comment]
@lemeurherve in case you are interested.

**Comment by lemeurherve** [comment]
Similar question as in https://github.com/jenkins-infra/incrementals-publisher/issues/22#issuecomment-1937246947, should all artifacts be in this output or just the first one is enough?

**Comment by timja** [comment]
plugin manager CLI would only be relevant for a plugin hpi.
So it would only be once but may need some inspecting to see which artifact it is

**Comment by lemeurherve** [comment]
Result:

<img width="500" alt="image" src="https://github.com/jenkins-infra/incrementals-publisher/assets/91831478/38b6972c-1c7b-4560-8564-7fb0025c3902">

**Comment by timja** [comment]
Thanks looks great this will definitely save some time!

**Comment by lemeurherve** [comment]
Better example:

<img width="559" alt="image" src="https://github.com/jenkins-infra/incrementals-publisher/assets/91831478/f6d57bf9-52c5-439c-a46c-fbd6ffe9c349">

**Comment by lemeurherve** [comment]
Last result with #95 on Jenkins Core (without any hpi): https://github.com/jenkinsci/jenkins/pull/8954/checks?check_run_id=21517622355

<details><summary>Output:</summary>

<img width="592" alt="image" src="https://github.com/jenkins-infra/incrementals-publisher/assets/91831478/bc0ca70a-21a1-4b6b-ab66-512548aaa264">

</details>

Another interesting case on Pipeline Model Definition plugin (multiple hpi): https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/693/checks?check_run_id=21514969890

<details><summary>Output:</summary>

<img width="615" alt="image" src="https://github.com/jenkins-infra/incrementals-publisher/assets/91831478/fc9ad25b-fbe3-41be-84d8-c439df18c443">

</details>
